# Generated by Django 5.0.6 on 2024-07-02 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('faena', models.CharField(max_length=100)),
                ('maquina', models.CharField(max_length=100)),
                ('trabajo', models.CharField(max_length=200)),
                ('horometro_inicial', models.IntegerField()),
                ('horometro_final', models.IntegerField()),
                ('total_horas', models.IntegerField()),
                ('petroleo_litros', models.FloatField()),
                ('aceite_tipo_litros', models.CharField(max_length=200)),
                ('observaciones', models.TextField()),
                ('aprobado', models.BooleanField(default=False)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisores', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
