# Generated by Django 5.0.6 on 2024-07-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_alter_trabajo_horometro_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='horometro_final',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='horometro_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
