# Generated by Django 5.0.6 on 2024-07-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_trabajo_horometro_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='horometro_final',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='horometro_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='total_horas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
