# Generated by Django 5.1.6 on 2025-04-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_remove_empresa_cantidad_faenas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='es_administrador',
            field=models.BooleanField(default=False),
        ),
    ]
