# Generated by Django 5.1.6 on 2025-04-14 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_perfilusuario_es_administrador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='es_administrador',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='registros.empresa'),
        ),
    ]
