# Generated by Django 5.0.6 on 2024-07-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_alter_trabajo_horometro_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='faena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.faena'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.maquina'),
        ),
    ]
