# Generated by Django 5.0.6 on 2024-07-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_faena_maquina_alter_trabajo_faena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='tipo_medida',
            field=models.CharField(choices=[('Horas', 'Horas'), ('Kilómetros', 'Kilómetros')], default='Horas', max_length=10),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='petroleo_litros',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
