# Generated by Django 5.1.6 on 2025-04-16 14:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_remove_perfilusuario_es_administrador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='aceite_litros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Litros de aceite'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='aceite_tipo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de aceite'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='empresa',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='registros.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='horometro_final',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horómetro/Km final'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='horometro_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horómetro/Km inicial'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='petroleo_litros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Litros de petróleo'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='total_horas',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True, verbose_name='Total Horas/Km'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador'),
        ),
    ]
