# Generated by Django 5.1.6 on 2025-04-02 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_trabajo_tipo_medida_alter_trabajo_petroleo_litros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_maquinas', models.PositiveIntegerField(default=0)),
                ('cantidad_faenas', models.PositiveIntegerField(default=0)),
                ('cantidad_usuarios', models.PositiveIntegerField(default=0)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_administradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
