# Generated by Django 5.1.6 on 2025-05-20 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_remove_maquina_estado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maquina',
            unique_together=set(),
        ),
    ]
