# Generated by Django 5.0.6 on 2024-09-26 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registros.empresa'),
            preserve_default=False,
        ),
    ]
