# Generated by Django 5.1.3 on 2025-05-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_alter_maquina_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='no_pago_fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de activación de No Pago'),
        ),
    ]
