# Generated by Django 5.0.6 on 2024-10-17 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_maquina_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='cantidad_empleados',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='cantidad_maquinas',
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.TextField(default='123'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rut',
            field=models.CharField(default='0000000000000', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faena',
            name='empresa',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='registros.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajo',
            name='empresa',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='registros.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registros.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
