# Generated by Django 5.0.6 on 2024-10-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_remove_empresa_administrador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='limite_faenas',
            field=models.PositiveIntegerField(default=0, help_text='Límite máximo de faenas permitidas'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='limite_maquinas',
            field=models.PositiveIntegerField(default=0, help_text='Límite máximo de máquinas permitidas'),
        ),
    ]
