# Generated by Django 5.1.3 on 2025-06-23 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_empresa_no_pago_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_supervisados', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='trabajador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador'),
        ),
    ]
