# Generated by Django 5.0.6 on 2024-10-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0010_empresa_limite_faenas_empresa_limite_maquinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='limite_usuarios',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='limite_faenas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='limite_maquinas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rut',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
